export default {
  albumCover: document.getElementsByClassName('album-cover'),
  closeModal : document.getElementById('close-modal-button'),
  creator : document.getElementById("creator"),
  errorMessage : document.getElementById('error-message'),
  info : document.getElementById('info'),
  infoModal : document.getElementById('info-modal'),
  input : document.querySelector('input'),
  loader : document.getElementById('loader'),
  openSpotify : document.getElementById('open-spotify-button'),
  playIcon : document.getElementsByClassName('play-icon'),
  playLink : document.getElementsByClassName('play-link'),
  searchBox : document.getElementById('search-box'),
  searchField : document.getElementById('artist-search-field'),
  searchForm : document.getElementById('artist-search-form'),
  toolTip : document.getElementsByClassName('tooltip'),
};
